import { Footer, Header } from '@/frontend-components';
import '../../public/assets/css/style.css';
import type { Metadata } from 'next';
import Script from 'next/script';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<link
				rel="stylesheet"
				href="https://unpkg.com/swiper/swiper-bundle.min.css"
			/>
			<Script
				src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
				strategy="beforeInteractive"
			/>

			<Header />
			{children}
			<Footer />
		</>
	);
}
